[package]
name = "ec-slimloader-mcxa-split"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
embedded-storage-async.workspace = true
cortex-m = "0.7"
embassy-mcxa = { workspace = true, features = ["rt", "mcxa5xx", "unstable-pac"] }
embassy-sync = "0.8.0"
embassy-embedded-hal = "0.6.0"
static_cell = "2.1.1"

ec-slimloader = { path = "../ec-slimloader", default-features = false, features = ["defmt"] }
ec-slimloader-state = { path = "../ec-slimloader-state", default-features = false }

[lints]
workspace = true
