[package]
name = "mcxa-577app-bootloader"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mcxa-577app-bootloader"
path = "src/main.rs"

[dependencies]
cortex-m = { version = "0.7", features = ["critical-section-single-core"], default-features = false }
cortex-m-rt = "0.7"
panic-halt = "1.0.0"
defmt = "1.1.1"
defmt-or-log = { version = "0.2.3", features = ["defmt"] }
defmt-rtt = "1.3.0"

ec-slimloader-mcxa-split = { path = "../../../libs/ec-slimloader-mcxa-split", features = ["defmt"] }
ec-slimloader = { path = "../../../libs/ec-slimloader", default-features = false }

embassy-executor = { git = "https://github.com/embassy-rs/embassy", default-features = false, features = ["platform-cortex-m", "executor-thread"] }

[profile.release]
debug = true
lto = true
opt-level = "z"
