[package]
name = "ec-slimloader-mcxa"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
device-driver.workspace = true
defmt = { workspace = true, optional = true }
defmt-or-log = { workspace = true, optional = true }
log = { workspace = true, optional = true }
ec-slimloader = { path = "../ec-slimloader", default-features = false }
ec-slimloader-state = { path = "../ec-slimloader-state", default-features = false }
cortex-m = "0.7"
embassy-sync = { workspace = true }
embassy-mcxa = { workspace = true, features = ["rt"] }
embedded-storage-async = { workspace = true }

[features]
default = ["internal-only", "mcxa5xx"]
internal-only = []
defmt = ["dep:defmt", "dep:defmt-or-log", "defmt-or-log/defmt", "ec-slimloader/defmt"]
log = ["dep:log", "dep:defmt-or-log", "defmt-or-log/log", "ec-slimloader/log"]
certificate-logging = []
verification-logging = []
mcxa2xx = ["embassy-mcxa/mcxa2xx"]
mcxa5xx = ["embassy-mcxa/mcxa5xx"]


