[package]
name = "ec-slimloader-mcxa"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
defmt = { workspace = true, optional = true }
defmt-or-log = { workspace = true }
log = { workspace = true, optional = true }
ec-slimloader = { path = "../ec-slimloader", default-features = false }
ec-slimloader-state = { path = "../ec-slimloader-state", default-features = false }
cortex-m.workspace = true
heapless = { workspace = true }
partition-manager = { workspace = true, features = ["esa"] }
partition-manager-macros = { workspace = true }
static_cell = { workspace = true }
embassy-sync = { workspace = true }
embassy-mcxa = { workspace = true, features = ["rt", "unstable-pac"] }
embedded-storage-async = { workspace = true }

[features]
default = ["mcxa5xx", "verification-logging", "certificate-logging", "defmt"]
defmt = ["dep:defmt", "defmt-or-log/defmt", "ec-slimloader/defmt"]
log = ["dep:log", "defmt-or-log/log", "ec-slimloader/log"]
certificate-logging = []
verification-logging = []
flexspi-selftest = []
mcxa2xx = ["embassy-mcxa/mcxa2xx"]
mcxa5xx = ["embassy-mcxa/mcxa5xx"]
# Use this when targeting the FRDM-MCXA577 EVK (flash on FlexSPI Port A).
# Without this flag the driver targets Port B (custom board wiring for end target HW).
mcxa5xxevk = []


