[package]
name = "mcxa-577app-bootloader"
version = "0.1.0"
edition = "2021"

[features]
default = ["defmt", "certificate-logging", "verification-logging", "mcxa"]
defmt = ["dep:defmt", "dep:defmt-or-log", "dep:defmt-rtt", "defmt-or-log/defmt"]
log = ["dep:defmt-or-log", "defmt-or-log/log"]
mcxa = ["ec-slimloader-mcxa/mcxa5xx"]
mcxa5xxevk = ["ec-slimloader-mcxa/mcxa5xxevk"]
certificate-logging = ["ec-slimloader-mcxa/certificate-logging"]
verification-logging = ["ec-slimloader-mcxa/verification-logging"]

[[bin]]
name = "bootloader"
path = "src/main.rs"

[dependencies]
cortex-m = { version = "0.7", features = ["critical-section-single-core"], default-features = false }
cortex-m-rt = "0.7"
defmt = { version = "1.0", optional = true }
defmt-or-log = { version = "0.2.3", optional = true }
defmt-rtt = { version = "1.0", optional = true }
panic-probe = { version = "1.0", features = ["print-defmt"] }

heapless = { version = "0.8", default-features = false }
partition-manager = { workspace = true, features = ["macros"] }
partition-manager-macros = { workspace = true }
embassy-sync = { workspace = true }

ec-slimloader-mcxa = { path = "../../../libs/ec-slimloader-mcxa", default-features = false, features = ["mcxa5xx", "defmt"] }
ec-slimloader = { path = "../../../libs/ec-slimloader", default-features = false }
ec-slimloader-state = { path = "../../../libs/ec-slimloader-state", default-features = false }
mcxa-security-provisioning = { path = "../../../libs/mcxa-security-provisioning", default-features = false, features = ["defmt"] }

embassy-mcxa = { workspace = true, features = ["rt", "mcxa5xx"] }
embassy-executor = { workspace = true, features = ["platform-cortex-m", "executor-thread"] }
