[workspace]
resolver = "3"
members = [
    "ec-slimloader",
    "ec-slimloader-imxrt",
    "ec-slimloader-state",
    "ec-slimloader-mcxa",
    "imxrt-rom",
    "mcxa-security-provisioning"
]

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/OpenDevicePartnership/ec-slimloader"

[workspace.lints.clippy]
manual_let_else = "deny"

[workspace.dependencies]
defmt = "0.3.7"
defmt-or-log = { version = "0.2.2", default-features = false }
log = "0.4"

cortex-m = { version = "0.7.7" }
panic-probe = "0.3"
arbitrary = "1.4"
crc = "3.2"
num_enum = { version = "0.7", default-features = false }
device-driver = "1.0"
embedded-storage-async = "0.4.1"
heapless = "0.8"
static_cell = "2.1"
partition-manager = { git = "https://github.com/OpenDevicePartnership/embedded-services.git", tag = "v0.1.0", default-features = false }
partition-manager-macros = { git = "https://github.com/OpenDevicePartnership/embedded-services.git", tag = "v0.1.0" }
embassy-sync = "0.8.0"
embassy-time = "0.5.0"
embassy-futures = "0.1.0"
embassy-mcxa = { git = "https://github.com/embassy-rs/embassy", rev = "f0fd6e2a8e9c505290498e316ad2bdda8b94da5e", default-features = false }
embassy-imxrt = { git = "https://github.com/OpenDevicePartnership/embassy-imxrt.git", default-features = false, features = [
    "mimxrt685s",
] }

[patch.crates-io]
embassy-time-driver = { git = "https://github.com/embassy-rs/embassy", rev = "f0fd6e2a8e9c505290498e316ad2bdda8b94da5e" }
