[workspace]
resolver = "3"
members = [
    "ec-slimloader",
    "ec-slimloader-imxrt",
    "ec-slimloader-state",
    "ec-slimloader-mcxa",
    "imxrt-rom",
]

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/OpenDevicePartnership/ec-slimloader"

[workspace.lints.clippy]
manual_let_else = "deny"

[workspace.dependencies]
defmt = "0.3.7"
defmt-or-log = { version = "0.2.2", default-features = false }
embedded-storage-async = "0.4.1"
embassy-futures = "0.1"
embassy-time = "0.5"
embassy-imxrt = { git = "https://github.com/OpenDevicePartnership/embassy-imxrt.git", default-features = false, features = ["mimxrt685s"] }
embassy-mcxa = { git = "https://github.com/embassy-rs/embassy", rev = "aca5a5466cf4d78708b3bdd56b62b8a1cf78a3a3", default-features = false }
embassy-sync = "0.8.0"
log = "0.4"

cortex-m = { version = "0.7.7" }
panic-probe = "0.3"
arbitrary = "1.4"
crc = "3.2"
num_enum = { version = "0.7", default-features = false }
device-driver = "1.0"
