[package]
name = "ec-slimloader-state"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
crc = { workspace = true }
num_enum = { workspace = true, default-features = false }

embedded-storage-async = { workspace = true }
defmt = { workspace = true, optional = true }
defmt-or-log = { workspace = true }
log = { workspace = true, optional = true }
arbitrary = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
embassy-futures = { workspace = true }

[features]
defmt = ["dep:defmt", "defmt-or-log/defmt"]
log = ["dep:log", "defmt-or-log/log"]

# Used for the fuzzing framework
_test = ["dep:arbitrary"]

default = []
